CC=gcc
FILENAME=CS323_dz01
SRC=source/
OUT=build/
cs323_dz01: $(SRC)main.c
	$(CC) $(SRC)main.c -o $(OUT)cs323_dz01 && $(OUT)cs323_dz01
build: $(SRC)main.c
	$(CC) $(SRC)main.c -o $(OUT)cs323_dz01
run:
	$(OUT)cs323_dz01