CC=gcc
FILENAME=CS323_v01
SRC=source/
OUT=build/
cs323_v01: $(SRC)main.c
	$(CC) $(SRC)main.c -o $(OUT)cs323_v01 && $(OUT)cs323_v01
build: $(SRC)main.c
	$(CC) $(SRC)main.c -o $(OUT)cs323_v01
run:
	$(OUT)cs323_v01