/**
 * Generated by nik on 04/01/2020
 */

#include "db/orm/address.h"


/* Generated function */
uint address_insert(MYSQL* conn, ADDRESS* addressT) {
	#define QUERY_LENGTH 512
	#define STRING_SIZE 255
	#define QUERY "insert into address (id_municipality, street, number) values (?, ?, ?);"
	#define PARAM_COUNT 3
	#define STREET_SIZE 256
	#define NUMBER_SIZE 9
	/* Generated using get_insert_assertions() */
	assert(addressT->id_address == 0);
	assert(strnlen(addressT->street, STRING_SIZE) > 1);
	assert(strnlen(addressT->number, STRING_SIZE) > 1);
	

	
	MYSQL_STMT* __attribute__((cleanup(mysql_stmt_cleanup))) stmt;
	uint retval;
	

	if (conn == NULL) {
		conn = db_init();
	}
	

	stmt = mysql_stmt_init(conn);
	

	/* Generated using get_update_fk() */
	
	if (addressT->municipality == NULL){
		fprintf(stderr, "%s->%s is NULL\n", "address", "municipality");
		return 0U;
	} else if (addressT->municipality->id_municipality == 0) {
		municipality_insert(conn, addressT->municipality);
	} else {
		municipality_update(conn, addressT->municipality);
	}

	/* Generated using col_param_lengths() */
	MYSQL_BIND param[PARAM_COUNT];
	memset(&param, 0, sizeof(param));
	
	unsigned long street_len;
	street_len = strnlen(addressT->street, STREET_SIZE);
	
	unsigned long number_len;
	number_len = strnlen(addressT->number, NUMBER_SIZE);
	

	/* Generated using get_col_param_buffers() */
	
	/* INTEGER PARAM */
	param[0].buffer = malloc(sizeof(uint));
	param[0].buffer_type = MYSQL_TYPE_LONG;
	memcpy(param[0].buffer, &addressT->municipality->id_municipality, sizeof(uint));
	/* STRING PARAM */
	param[1].buffer = malloc(street_len);
	param[1].buffer_type = MYSQL_TYPE_STRING;
	param[1].buffer_length = street_len;
	strncpy(param[1].buffer, addressT->street, street_len);
	/* STRING PARAM */
	param[2].buffer = malloc(number_len);
	param[2].buffer_type = MYSQL_TYPE_STRING;
	param[2].buffer_length = number_len;
	strncpy(param[2].buffer, addressT->number, number_len);

	if (mysql_stmt_prepare(stmt, QUERY, QUERY_LENGTH)) {
		fprintf(stderr, " mysql_stmt_prepare(), failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return 0U;
	}

	if (mysql_stmt_bind_param(stmt, param)) {
		fprintf(stderr, " mysql_stmt_bind_param(), failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return 0U;
	}

	if (mysql_stmt_execute(stmt)) {
		fprintf(stderr, " mysql_stmt_execute(), failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return 0U;
	}

	retval = (uint) mysql_stmt_insert_id(stmt);

	// update id after insertion;
	addressT->id_address = retval;
	

	/* Generated using col_param_buffer_free() */
	free(param[0].buffer);
	free(param[1].buffer);
	free(param[2].buffer);
	

	return retval;

	#undef QUERY_LENGTH
	#undef STRING_SIZE
	#undef QUERY
	#undef PARAM_COUNT
	#undef STREET_SIZE
	#undef NUMBER_SIZE
}


/* Generated function */
SQL_RESULT* address_execute_find(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count) {
	#define QUERY_SIZE 512
	#define RES_COL_COUNT 4
	#define BUFFER_SIZE 255
	
	SQL_RESULT* res;
	MYSQL_RES* prepare_meta_result;
	MYSQL_STMT* stmt;

	if (conn == NULL) {
		conn = db_init();
	}
	

	/* Generated using get_col_buffer_definitions()*/
	unsigned long lengths[RES_COL_COUNT];
	my_bool is_null[RES_COL_COUNT];
	my_bool error[RES_COL_COUNT];
	uint id_address_buffer;
	uint id_municipality_buffer;
	char street_buffer[256];
	char number_buffer[9];
	

	stmt = mysql_stmt_init(conn);

	if (mysql_stmt_prepare(stmt, query, strnlen(query, QUERY_SIZE))) {
		fprintf(stderr, " mysql_stmt_prepare(), SELECT failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return NULL;
	}
	mysql_stmt_bind_param(stmt, params);
	assert(param_count == mysql_stmt_param_count(stmt));

	/* Fetch result set meta information */
	prepare_meta_result = mysql_stmt_result_metadata(stmt);
	if (!prepare_meta_result) {
		fprintf(stderr, " mysql_stmt_result_metadata(), returned no meta information\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return NULL;
	}
	assert(RES_COL_COUNT == mysql_num_fields(prepare_meta_result));

	/* Execute the SELECT query */
	if (mysql_stmt_execute(stmt)) {
		fprintf(stderr, " mysql_stmt_execute(), failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return NULL;
	}

	/* Generated using get_buffer_bindings()*/
	MYSQL_BIND param[RES_COL_COUNT];
	memset(param, 0, sizeof(param));
	
	/* INTEGER COLUMN */
	param[0].buffer_type = MYSQL_TYPE_LONG;
	param[0].buffer = &id_address_buffer;
	param[0].is_null = &is_null[0];
	param[0].length = &lengths[0];
	param[0].error = &error[0];
	
	/* INTEGER COLUMN */
	param[1].buffer_type = MYSQL_TYPE_LONG;
	param[1].buffer = &id_municipality_buffer;
	param[1].is_null = &is_null[1];
	param[1].length = &lengths[1];
	param[1].error = &error[1];
	
	/* STRING COLUMN */
	param[2].buffer_type = MYSQL_TYPE_STRING;
	param[2].buffer = &street_buffer;
	param[2].is_null = &is_null[2];
	param[2].length = &lengths[2];
	param[2].error = &error[2];
	param[2].buffer_length = 256;
	
	/* STRING COLUMN */
	param[3].buffer_type = MYSQL_TYPE_STRING;
	param[3].buffer = &number_buffer;
	param[3].is_null = &is_null[3];
	param[3].length = &lengths[3];
	param[3].error = &error[3];
	param[3].buffer_length = 9;
	

	/* Bind the result buffers */
	if (mysql_stmt_bind_result(stmt, param)) {
		fprintf(stderr, " mysql_stmt_bind_result() failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return NULL;
	}

	/* Now buffer all results to client (optional step) */
	if (mysql_stmt_store_result(stmt)) {
		fprintf(stderr, " mysql_stmt_store_result() failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return NULL;
	}

	/* Fetch all rows */
	struct sql_result_row* row = NULL;
	struct sql_result_row* curr = NULL;
	
	res = calloc(1, sizeof(SQL_RESULT));
	res->results = NULL;
	res->type = ADDRESS_E;
	res->count = 0;

	
	/* Generated using col_fetch()*/
	while (!mysql_stmt_fetch(stmt)) {
		res->count++;
		row = calloc(1, sizeof(struct sql_result_row));
		if (res->results == NULL) {
			res->results = row;
		} else {
			curr = res->results;
			while (curr->next != NULL) {
				curr = curr->next;
			}
			curr->next = row;
		}
		row->data = calloc(1, sizeof(ADDRESS));
		
		if (is_null[0]) {
			((ADDRESS*) row->data)->id_address = 0;
		} else {
			((ADDRESS*) row->data)->id_address = id_address_buffer;
		}
		if (is_null[1]) {
			((ADDRESS*) row->data)->municipality = NULL;
		} else {
			((ADDRESS*) row->data)->municipality = municipality_find_by_id(conn, id_municipality_buffer);
		}
		if (is_null[2]) {
			strcpy(((ADDRESS*) row->data)->street, "NULL");
		} else {
			strncpy(((ADDRESS*) row->data)->street, street_buffer, lengths[2]);
		}
		if (is_null[3]) {
			strcpy(((ADDRESS*) row->data)->number, "NULL");
		} else {
			strncpy(((ADDRESS*) row->data)->number, number_buffer, lengths[3]);
		}
	}

	/* Free the prepared result metadata */
	mysql_free_result(prepare_meta_result);
	if (mysql_stmt_close(stmt)) {
		fprintf(stderr, " failed while closing the statement\n");
		fprintf(stderr, " %s\n", mysql_error(conn));
		mysql_res_free(&res);
		return NULL;
	}

	return res;

	#undef QUERY_SIZE
	#undef RES_COL_COUNT
	#undef BUFFER_SIZE
}


/* Generated function */
ADDRESS* address_find_by_id(MYSQL* conn, uint id) {
	#define QUERY "select * from address where id_address = ?;"
	#define PARAM_COUNT 1
	if (conn == NULL) {
		conn = db_init();
	}
	

	ADDRESS* out;

	
	SQL_RESULT* res;
	struct address address;
	address.id_address = id;
	struct address* addressT = &address;
	

	/* Generated using  get_col_param_buffers() */
	MYSQL_BIND param[PARAM_COUNT];
	memset(param, 0, sizeof(param));
	
	/* INTEGER PARAM */
	param[0].buffer = malloc(sizeof(uint));
	param[0].buffer_type = MYSQL_TYPE_LONG;
	memcpy(param[0].buffer, &addressT->id_address, sizeof(uint));

	res = address_execute_find(conn, QUERY, param, PARAM_COUNT);

	/* Generated using col_param_buffer_free() */
	free(param[0].buffer);
	

if (res->results == NULL) { return NULL; }

	out = res->results->data;
	if (res->count == 1) {
		free(res->results);
		free(res);
		return out;
	} else {
		fprintf(stderr, "address_execute_find(), failed - multiple results (%d)\n", res->count);
		mysql_res_free(&res);
		return NULL;
	}

	#undef QUERY
	#undef PARAM_COUNT
}


/* Generated function */
int address_update(MYSQL* conn, ADDRESS* addressT) {
	#define QUERY "update address set id_municipality = ?, street = ?, number = ? where id_address = ?;"
	#define PARAM_COUNT 4
	#define STRING_SIZE 255
	#define STREET_SIZE 256
	#define NUMBER_SIZE 9
	assert(addressT->id_address != 0);

	if (conn == NULL) {
		conn = db_init();
	}
	

	int retval;

	/* Generated using col_update_params() */
	MYSQL_BIND param[PARAM_COUNT];
	memset(&param, 0, sizeof(param));
	
	unsigned long street_len;
	street_len = strnlen(addressT->street, STREET_SIZE);
	
	unsigned long number_len;
	number_len = strnlen(addressT->number, NUMBER_SIZE);
	
	/* INTEGER PARAM */
	param[0].buffer = malloc(sizeof(uint));
	param[0].buffer_type = MYSQL_TYPE_LONG;
	memcpy(param[0].buffer, &addressT->municipality->id_municipality, sizeof(uint));
	/* STRING PARAM */
	param[1].buffer = malloc(street_len);
	param[1].buffer_type = MYSQL_TYPE_STRING;
	param[1].buffer_length = street_len;
	strncpy(param[1].buffer, addressT->street, street_len);
	/* STRING PARAM */
	param[2].buffer = malloc(number_len);
	param[2].buffer_type = MYSQL_TYPE_STRING;
	param[2].buffer_length = number_len;
	strncpy(param[2].buffer, addressT->number, number_len);
	/* INTEGER PARAM */
	param[3].buffer = malloc(sizeof(uint));
	param[3].buffer_type = MYSQL_TYPE_LONG;
	memcpy(param[3].buffer, &addressT->id_address, sizeof(uint));

	retval = address_execute(conn, QUERY, param, PARAM_COUNT);

	/* Generated using col_buffer_free() */
	free(param[0].buffer);
	free(param[1].buffer);
	free(param[2].buffer);
	free(param[3].buffer);
	

	return retval;

	#undef QUERY
	#undef PARAM_COUNT
	#undef STRING_SIZE
	#undef STREET_SIZE
	#undef NUMBER_SIZE
}


/* Generated function */
int address_execute(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count) {
	#define QUERY_LENGTH 512
	/* Generated by body_execute */

	MYSQL_STMT* stmt;
	int retval;

	if (conn == NULL) {
		conn = db_init();
	}
	

	
	stmt = mysql_stmt_init(conn);

	if ((retval = mysql_stmt_prepare(stmt, query, strnlen(query, QUERY_LENGTH)))) {
		fprintf(stderr, "mysql_stmt_prepare(), failed\n");
		fprintf(stderr, "%s\n", mysql_error(conn));
		return retval;
	}

	if ((retval = mysql_stmt_bind_param(stmt, params))) {
		fprintf(stderr, "mysql_stmt_bind_param(), failed\n");
		fprintf(stderr, "%s\n", mysql_error(conn));
		return retval;
	}

	if ((retval = mysql_stmt_execute(stmt))) {
		fprintf(stderr, "mysql_stmt_execute(), failed\n");
		fprintf(stderr, "%s\n", mysql_error(conn));
		return retval;
	}

	if ((retval = mysql_stmt_close(stmt))) {
		fprintf(stderr, " failed while closing the statement\n");
		fprintf(stderr, " %s\n", mysql_error(conn));
		return retval;
	}

	#undef QUERY_LENGTH
}


/* Generated function */
int address_delete(MYSQL* conn, ADDRESS* addressT) {
	#define QUERY "delete from address where id_address = ?;"
	#define PARAM_COUNT 1
	assert(addressT->id_address != 0);

	if (conn == NULL) {
		conn = db_init();
	}
	

	int retval;

	/* Generated using  get_col_param_buffers() */
	MYSQL_BIND param[PARAM_COUNT];
	memset(param, 0, sizeof(param));
	
	/* INTEGER PARAM */
	param[0].buffer = malloc(sizeof(uint));
	param[0].buffer_type = MYSQL_TYPE_LONG;
	memcpy(param[0].buffer, &addressT->id_address, sizeof(uint));

	retval = address_execute(conn, QUERY, param, PARAM_COUNT);

	/* Generated using col_param_buffer_free() */
	free(param[0].buffer);
	

	return retval;

	#undef QUERY
	#undef PARAM_COUNT
}


/* Generated function */
SQL_RESULT* address_find_all(MYSQL* conn) {
	#define QUERY "select * from address;"
	#define PARAM_COUNT 0
	SQL_RESULT* res;

	MYSQL_BIND param[1];

	if (conn == NULL) {
		conn = db_init();
	}
	

	res = address_execute_find(conn, QUERY, param, PARAM_COUNT);

	return res;

	#undef QUERY
	#undef PARAM_COUNT
}


/* Generated function */
void address_free(ADDRESS** ptr) {
	/* Generated by get_free_members() */
	assert(ptr != NULL);
	
	if (*ptr != NULL){
		municipality_free(&((*ptr)->municipality));
		free(*ptr);
	}

}
