/**
 * Generated by nik on 04/01/2020
 */

#include "db/orm/reader.h"


/* Generated function */
uint reader_insert(MYSQL* conn, READER* readerT) {
	#define QUERY_LENGTH 512
	#define STRING_SIZE 255
	#define QUERY "insert into reader (username, password) values (?, ?);"
	#define PARAM_COUNT 2
	#define USERNAME_SIZE 256
	#define PASSWORD_SIZE 256
	/* Generated using get_insert_assertions() */
	assert(readerT->id_reader == 0);
	assert(strnlen(readerT->username, STRING_SIZE) > 1);
	assert(strnlen(readerT->password, STRING_SIZE) > 1);
	

	
	MYSQL_STMT* __attribute__((cleanup(mysql_stmt_cleanup))) stmt;
	uint retval;
	

	if (conn == NULL) {
		conn = db_init();
	}
	

	stmt = mysql_stmt_init(conn);
	

	/* Generated using get_update_fk() */
	

	/* Generated using col_param_lengths() */
	MYSQL_BIND param[PARAM_COUNT];
	memset(&param, 0, sizeof(param));
	
	unsigned long username_len;
	username_len = strnlen(readerT->username, USERNAME_SIZE);
	
	unsigned long password_len;
	password_len = strnlen(readerT->password, PASSWORD_SIZE);
	

	/* Generated using get_col_param_buffers() */
	
	/* STRING PARAM */
	param[0].buffer = malloc(username_len);
	param[0].buffer_type = MYSQL_TYPE_STRING;
	param[0].buffer_length = username_len;
	strncpy(param[0].buffer, readerT->username, username_len);
	/* STRING PARAM */
	param[1].buffer = malloc(password_len);
	param[1].buffer_type = MYSQL_TYPE_STRING;
	param[1].buffer_length = password_len;
	strncpy(param[1].buffer, readerT->password, password_len);

	if (mysql_stmt_prepare(stmt, QUERY, QUERY_LENGTH)) {
		fprintf(stderr, " mysql_stmt_prepare(), failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return 0U;
	}

	if (mysql_stmt_bind_param(stmt, param)) {
		fprintf(stderr, " mysql_stmt_bind_param(), failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return 0U;
	}

	if (mysql_stmt_execute(stmt)) {
		fprintf(stderr, " mysql_stmt_execute(), failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return 0U;
	}

	retval = (uint) mysql_stmt_insert_id(stmt);

	// update id after insertion;
	readerT->id_reader = retval;
	

	/* Generated using col_param_buffer_free() */
	free(param[0].buffer);
	free(param[1].buffer);
	

	return retval;

	#undef QUERY_LENGTH
	#undef STRING_SIZE
	#undef QUERY
	#undef PARAM_COUNT
	#undef USERNAME_SIZE
	#undef PASSWORD_SIZE
}


/* Generated function */
SQL_RESULT* reader_execute_find(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count) {
	#define QUERY_SIZE 512
	#define RES_COL_COUNT 3
	#define BUFFER_SIZE 255
	
	SQL_RESULT* res;
	MYSQL_RES* prepare_meta_result;
	MYSQL_STMT* stmt;

	if (conn == NULL) {
		conn = db_init();
	}
	

	/* Generated using get_col_buffer_definitions()*/
	unsigned long lengths[RES_COL_COUNT];
	my_bool is_null[RES_COL_COUNT];
	my_bool error[RES_COL_COUNT];
	uint id_reader_buffer;
	char username_buffer[256];
	char password_buffer[256];
	

	stmt = mysql_stmt_init(conn);

	if (mysql_stmt_prepare(stmt, query, strnlen(query, QUERY_SIZE))) {
		fprintf(stderr, " mysql_stmt_prepare(), SELECT failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return NULL;
	}
	mysql_stmt_bind_param(stmt, params);
	assert(param_count == mysql_stmt_param_count(stmt));

	/* Fetch result set meta information */
	prepare_meta_result = mysql_stmt_result_metadata(stmt);
	if (!prepare_meta_result) {
		fprintf(stderr, " mysql_stmt_result_metadata(), returned no meta information\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return NULL;
	}
	assert(RES_COL_COUNT == mysql_num_fields(prepare_meta_result));

	/* Execute the SELECT query */
	if (mysql_stmt_execute(stmt)) {
		fprintf(stderr, " mysql_stmt_execute(), failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return NULL;
	}

	/* Generated using get_buffer_bindings()*/
	MYSQL_BIND param[RES_COL_COUNT];
	memset(param, 0, sizeof(param));
	
	/* INTEGER COLUMN */
	param[0].buffer_type = MYSQL_TYPE_LONG;
	param[0].buffer = &id_reader_buffer;
	param[0].is_null = &is_null[0];
	param[0].length = &lengths[0];
	param[0].error = &error[0];
	
	/* STRING COLUMN */
	param[1].buffer_type = MYSQL_TYPE_STRING;
	param[1].buffer = &username_buffer;
	param[1].is_null = &is_null[1];
	param[1].length = &lengths[1];
	param[1].error = &error[1];
	param[1].buffer_length = 256;
	
	/* STRING COLUMN */
	param[2].buffer_type = MYSQL_TYPE_STRING;
	param[2].buffer = &password_buffer;
	param[2].is_null = &is_null[2];
	param[2].length = &lengths[2];
	param[2].error = &error[2];
	param[2].buffer_length = 256;
	

	/* Bind the result buffers */
	if (mysql_stmt_bind_result(stmt, param)) {
		fprintf(stderr, " mysql_stmt_bind_result() failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return NULL;
	}

	/* Now buffer all results to client (optional step) */
	if (mysql_stmt_store_result(stmt)) {
		fprintf(stderr, " mysql_stmt_store_result() failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return NULL;
	}

	/* Fetch all rows */
	struct sql_result_row* row = NULL;
	struct sql_result_row* curr = NULL;
	
	res = calloc(1, sizeof(SQL_RESULT));
	res->results = NULL;
	res->type = READER_E;
	res->count = 0;

	
	/* Generated using col_fetch()*/
	while (!mysql_stmt_fetch(stmt)) {
		res->count++;
		row = calloc(1, sizeof(struct sql_result_row));
		if (res->results == NULL) {
			res->results = row;
		} else {
			curr = res->results;
			while (curr->next != NULL) {
				curr = curr->next;
			}
			curr->next = row;
		}
		row->data = calloc(1, sizeof(READER));
		
		if (is_null[0]) {
			((READER*) row->data)->id_reader = 0;
		} else {
			((READER*) row->data)->id_reader = id_reader_buffer;
		}
		if (is_null[1]) {
			strcpy(((READER*) row->data)->username, "NULL");
		} else {
			strncpy(((READER*) row->data)->username, username_buffer, lengths[1]);
		}
		if (is_null[2]) {
			strcpy(((READER*) row->data)->password, "NULL");
		} else {
			strncpy(((READER*) row->data)->password, password_buffer, lengths[2]);
		}
	}

	/* Free the prepared result metadata */
	mysql_free_result(prepare_meta_result);
	if (mysql_stmt_close(stmt)) {
		fprintf(stderr, " failed while closing the statement\n");
		fprintf(stderr, " %s\n", mysql_error(conn));
		mysql_res_free(&res);
		return NULL;
	}

	return res;

	#undef QUERY_SIZE
	#undef RES_COL_COUNT
	#undef BUFFER_SIZE
}


/* Generated function */
READER* reader_find_by_id(MYSQL* conn, uint id) {
	#define QUERY "select * from reader where id_reader = ?;"
	#define PARAM_COUNT 1
	if (conn == NULL) {
		conn = db_init();
	}
	

	READER* out;

	
	SQL_RESULT* res;
	struct reader reader;
	reader.id_reader = id;
	struct reader* readerT = &reader;
	

	/* Generated using  get_col_param_buffers() */
	MYSQL_BIND param[PARAM_COUNT];
	memset(param, 0, sizeof(param));
	
	/* INTEGER PARAM */
	param[0].buffer = malloc(sizeof(uint));
	param[0].buffer_type = MYSQL_TYPE_LONG;
	memcpy(param[0].buffer, &readerT->id_reader, sizeof(uint));

	res = reader_execute_find(conn, QUERY, param, PARAM_COUNT);

	/* Generated using col_param_buffer_free() */
	free(param[0].buffer);
	

if (res->results == NULL) { return NULL; }

	out = res->results->data;
	if (res->count == 1) {
		free(res->results);
		free(res);
		return out;
	} else {
		fprintf(stderr, "reader_execute_find(), failed - multiple results (%d)\n", res->count);
		mysql_res_free(&res);
		return NULL;
	}

	#undef QUERY
	#undef PARAM_COUNT
}


/* Generated function */
int reader_update(MYSQL* conn, READER* readerT) {
	#define QUERY "update reader set username = ?, password = ? where id_reader = ?;"
	#define PARAM_COUNT 3
	#define STRING_SIZE 255
	#define USERNAME_SIZE 256
	#define PASSWORD_SIZE 256
	assert(readerT->id_reader != 0);

	if (conn == NULL) {
		conn = db_init();
	}
	

	int retval;

	/* Generated using col_update_params() */
	MYSQL_BIND param[PARAM_COUNT];
	memset(&param, 0, sizeof(param));
	
	unsigned long username_len;
	username_len = strnlen(readerT->username, USERNAME_SIZE);
	
	unsigned long password_len;
	password_len = strnlen(readerT->password, PASSWORD_SIZE);
	
	/* STRING PARAM */
	param[0].buffer = malloc(username_len);
	param[0].buffer_type = MYSQL_TYPE_STRING;
	param[0].buffer_length = username_len;
	strncpy(param[0].buffer, readerT->username, username_len);
	/* STRING PARAM */
	param[1].buffer = malloc(password_len);
	param[1].buffer_type = MYSQL_TYPE_STRING;
	param[1].buffer_length = password_len;
	strncpy(param[1].buffer, readerT->password, password_len);
	/* INTEGER PARAM */
	param[2].buffer = malloc(sizeof(uint));
	param[2].buffer_type = MYSQL_TYPE_LONG;
	memcpy(param[2].buffer, &readerT->id_reader, sizeof(uint));

	retval = reader_execute(conn, QUERY, param, PARAM_COUNT);

	/* Generated using col_buffer_free() */
	free(param[0].buffer);
	free(param[1].buffer);
	free(param[2].buffer);
	

	return retval;

	#undef QUERY
	#undef PARAM_COUNT
	#undef STRING_SIZE
	#undef USERNAME_SIZE
	#undef PASSWORD_SIZE
}


/* Generated function */
int reader_execute(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count) {
	#define QUERY_LENGTH 512
	/* Generated by body_execute */

	MYSQL_STMT* stmt;
	int retval;

	if (conn == NULL) {
		conn = db_init();
	}
	

	
	stmt = mysql_stmt_init(conn);

	if ((retval = mysql_stmt_prepare(stmt, query, strnlen(query, QUERY_LENGTH)))) {
		fprintf(stderr, "mysql_stmt_prepare(), failed\n");
		fprintf(stderr, "%s\n", mysql_error(conn));
		return retval;
	}

	if ((retval = mysql_stmt_bind_param(stmt, params))) {
		fprintf(stderr, "mysql_stmt_bind_param(), failed\n");
		fprintf(stderr, "%s\n", mysql_error(conn));
		return retval;
	}

	if ((retval = mysql_stmt_execute(stmt))) {
		fprintf(stderr, "mysql_stmt_execute(), failed\n");
		fprintf(stderr, "%s\n", mysql_error(conn));
		return retval;
	}

	if ((retval = mysql_stmt_close(stmt))) {
		fprintf(stderr, " failed while closing the statement\n");
		fprintf(stderr, " %s\n", mysql_error(conn));
		return retval;
	}

	#undef QUERY_LENGTH
}


/* Generated function */
int reader_delete(MYSQL* conn, READER* readerT) {
	#define QUERY "delete from reader where id_reader = ?;"
	#define PARAM_COUNT 1
	assert(readerT->id_reader != 0);

	if (conn == NULL) {
		conn = db_init();
	}
	

	int retval;

	/* Generated using  get_col_param_buffers() */
	MYSQL_BIND param[PARAM_COUNT];
	memset(param, 0, sizeof(param));
	
	/* INTEGER PARAM */
	param[0].buffer = malloc(sizeof(uint));
	param[0].buffer_type = MYSQL_TYPE_LONG;
	memcpy(param[0].buffer, &readerT->id_reader, sizeof(uint));

	retval = reader_execute(conn, QUERY, param, PARAM_COUNT);

	/* Generated using col_param_buffer_free() */
	free(param[0].buffer);
	

	return retval;

	#undef QUERY
	#undef PARAM_COUNT
}


/* Generated function */
SQL_RESULT* reader_find_all(MYSQL* conn) {
	#define QUERY "select * from reader;"
	#define PARAM_COUNT 0
	SQL_RESULT* res;

	MYSQL_BIND param[1];

	if (conn == NULL) {
		conn = db_init();
	}
	

	res = reader_execute_find(conn, QUERY, param, PARAM_COUNT);

	return res;

	#undef QUERY
	#undef PARAM_COUNT
}


/* Generated function */
void reader_free(READER** ptr) {
	/* Generated by get_free_members() */
	assert(ptr != NULL);
	
	if (*ptr != NULL){
		free(*ptr);
	}

}
