/**
 * Generated by nik on 04/01/2020
 */

#include "db/orm/rent.h"


/* Generated function */
uint rent_insert(MYSQL* conn, RENT* rentT) {
	#define QUERY_LENGTH 512
	#define STRING_SIZE 255
	#define QUERY "insert into rent (id_reader, id_book_specimen, due_date) values (?, ?, ?);"
	#define PARAM_COUNT 3
	/* Generated using get_insert_assertions() */
	assert(rentT->id_rent == 0);
	

	
	MYSQL_STMT* __attribute__((cleanup(mysql_stmt_cleanup))) stmt;
	uint retval;
	

	if (conn == NULL) {
		conn = db_init();
	}
	

	stmt = mysql_stmt_init(conn);
	

	/* Generated using get_update_fk() */
	
	if (rentT->reader == NULL){
		fprintf(stderr, "%s->%s is NULL\n", "rent", "reader");
		return 0U;
	} else if (rentT->reader->id_reader == 0) {
		reader_insert(conn, rentT->reader);
	} else {
		reader_update(conn, rentT->reader);
	}
	if (rentT->book_specimen == NULL){
		fprintf(stderr, "%s->%s is NULL\n", "rent", "book_specimen");
		return 0U;
	} else if (rentT->book_specimen->id_book_specimen == 0) {
		book_specimen_insert(conn, rentT->book_specimen);
	} else {
		book_specimen_update(conn, rentT->book_specimen);
	}

	/* Generated using col_param_lengths() */
	MYSQL_BIND param[PARAM_COUNT];
	memset(&param, 0, sizeof(param));
	

	/* Generated using get_col_param_buffers() */
	
	/* INTEGER PARAM */
	param[0].buffer = malloc(sizeof(uint));
	param[0].buffer_type = MYSQL_TYPE_LONG;
	memcpy(param[0].buffer, &rentT->reader->id_reader, sizeof(uint));
	/* INTEGER PARAM */
	param[1].buffer = malloc(sizeof(uint));
	param[1].buffer_type = MYSQL_TYPE_LONG;
	memcpy(param[1].buffer, &rentT->book_specimen->id_book_specimen, sizeof(uint));
	/* DATE PARAM */
	param[2].buffer = malloc(56);
	param[2].buffer_type = MYSQL_TYPE_DATE;
	mysql_timecpy(param[2].buffer, &rentT->due_date);

	if (mysql_stmt_prepare(stmt, QUERY, QUERY_LENGTH)) {
		fprintf(stderr, " mysql_stmt_prepare(), failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return 0U;
	}

	if (mysql_stmt_bind_param(stmt, param)) {
		fprintf(stderr, " mysql_stmt_bind_param(), failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return 0U;
	}

	if (mysql_stmt_execute(stmt)) {
		fprintf(stderr, " mysql_stmt_execute(), failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return 0U;
	}

	retval = (uint) mysql_stmt_insert_id(stmt);

	// update id after insertion;
	rentT->id_rent = retval;
	

	/* Generated using col_param_buffer_free() */
	free(param[0].buffer);
	free(param[1].buffer);
	free(param[2].buffer);
	

	return retval;

	#undef QUERY_LENGTH
	#undef STRING_SIZE
	#undef QUERY
	#undef PARAM_COUNT
}


/* Generated function */
SQL_RESULT* rent_execute_find(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count) {
	#define QUERY_SIZE 512
	#define RES_COL_COUNT 4
	#define BUFFER_SIZE 255
	
	SQL_RESULT* res;
	MYSQL_RES* prepare_meta_result;
	MYSQL_STMT* stmt;

	if (conn == NULL) {
		conn = db_init();
	}
	

	/* Generated using get_col_buffer_definitions()*/
	unsigned long lengths[RES_COL_COUNT];
	my_bool is_null[RES_COL_COUNT];
	my_bool error[RES_COL_COUNT];
	uint id_rent_buffer;
	uint id_reader_buffer;
	uint id_book_specimen_buffer;
	char due_date_buffer[56];
	

	stmt = mysql_stmt_init(conn);

	if (mysql_stmt_prepare(stmt, query, strnlen(query, QUERY_SIZE))) {
		fprintf(stderr, " mysql_stmt_prepare(), SELECT failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return NULL;
	}
	mysql_stmt_bind_param(stmt, params);
	assert(param_count == mysql_stmt_param_count(stmt));

	/* Fetch result set meta information */
	prepare_meta_result = mysql_stmt_result_metadata(stmt);
	if (!prepare_meta_result) {
		fprintf(stderr, " mysql_stmt_result_metadata(), returned no meta information\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return NULL;
	}
	assert(RES_COL_COUNT == mysql_num_fields(prepare_meta_result));

	/* Execute the SELECT query */
	if (mysql_stmt_execute(stmt)) {
		fprintf(stderr, " mysql_stmt_execute(), failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return NULL;
	}

	/* Generated using get_buffer_bindings()*/
	MYSQL_BIND param[RES_COL_COUNT];
	memset(param, 0, sizeof(param));
	
	/* INTEGER COLUMN */
	param[0].buffer_type = MYSQL_TYPE_LONG;
	param[0].buffer = &id_rent_buffer;
	param[0].is_null = &is_null[0];
	param[0].length = &lengths[0];
	param[0].error = &error[0];
	
	/* INTEGER COLUMN */
	param[1].buffer_type = MYSQL_TYPE_LONG;
	param[1].buffer = &id_reader_buffer;
	param[1].is_null = &is_null[1];
	param[1].length = &lengths[1];
	param[1].error = &error[1];
	
	/* INTEGER COLUMN */
	param[2].buffer_type = MYSQL_TYPE_LONG;
	param[2].buffer = &id_book_specimen_buffer;
	param[2].is_null = &is_null[2];
	param[2].length = &lengths[2];
	param[2].error = &error[2];
	
	/* DATE COLUMN */
	param[3].buffer_type = MYSQL_TYPE_STRING;
	param[3].buffer = &due_date_buffer;
	param[3].is_null = &is_null[3];
	param[3].length = &lengths[3];
	param[3].error = &error[3];
	param[3].buffer_length = BUFFER_SIZE;
	

	/* Bind the result buffers */
	if (mysql_stmt_bind_result(stmt, param)) {
		fprintf(stderr, " mysql_stmt_bind_result() failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return NULL;
	}

	/* Now buffer all results to client (optional step) */
	if (mysql_stmt_store_result(stmt)) {
		fprintf(stderr, " mysql_stmt_store_result() failed\n");
		fprintf(stderr, " %s\n", mysql_stmt_error(stmt));
		return NULL;
	}

	/* Fetch all rows */
	struct sql_result_row* row = NULL;
	struct sql_result_row* curr = NULL;
	
	res = calloc(1, sizeof(SQL_RESULT));
	res->results = NULL;
	res->type = RENT_E;
	res->count = 0;

	
	/* Generated using col_fetch()*/
	while (!mysql_stmt_fetch(stmt)) {
		res->count++;
		row = calloc(1, sizeof(struct sql_result_row));
		if (res->results == NULL) {
			res->results = row;
		} else {
			curr = res->results;
			while (curr->next != NULL) {
				curr = curr->next;
			}
			curr->next = row;
		}
		row->data = calloc(1, sizeof(RENT));
		
		if (is_null[0]) {
			((RENT*) row->data)->id_rent = 0;
		} else {
			((RENT*) row->data)->id_rent = id_rent_buffer;
		}
		if (is_null[1]) {
			((RENT*) row->data)->reader = NULL;
		} else {
			((RENT*) row->data)->reader = reader_find_by_id(conn, id_reader_buffer);
		}
		if (is_null[2]) {
			((RENT*) row->data)->book_specimen = NULL;
		} else {
			((RENT*) row->data)->book_specimen = book_specimen_find_by_id(conn, id_book_specimen_buffer);
		}
		if (is_null[3]) {
			// strcpy(((RENT*) row->data)->due_date, "NULL");
		} else {
			mysql_timecpystr(&((RENT*) row->data)->due_date, due_date_buffer);
		}
	}

	/* Free the prepared result metadata */
	mysql_free_result(prepare_meta_result);
	if (mysql_stmt_close(stmt)) {
		fprintf(stderr, " failed while closing the statement\n");
		fprintf(stderr, " %s\n", mysql_error(conn));
		mysql_res_free(&res);
		return NULL;
	}

	return res;

	#undef QUERY_SIZE
	#undef RES_COL_COUNT
	#undef BUFFER_SIZE
}


/* Generated function */
RENT* rent_find_by_id(MYSQL* conn, uint id) {
	#define QUERY "select * from rent where id_rent = ?;"
	#define PARAM_COUNT 1
	if (conn == NULL) {
		conn = db_init();
	}
	

	RENT* out;

	
	SQL_RESULT* res;
	struct rent rent;
	rent.id_rent = id;
	struct rent* rentT = &rent;
	

	/* Generated using  get_col_param_buffers() */
	MYSQL_BIND param[PARAM_COUNT];
	memset(param, 0, sizeof(param));
	
	/* INTEGER PARAM */
	param[0].buffer = malloc(sizeof(uint));
	param[0].buffer_type = MYSQL_TYPE_LONG;
	memcpy(param[0].buffer, &rentT->id_rent, sizeof(uint));

	res = rent_execute_find(conn, QUERY, param, PARAM_COUNT);

	/* Generated using col_param_buffer_free() */
	free(param[0].buffer);
	

if (res->results == NULL) { return NULL; }

	out = res->results->data;
	if (res->count == 1) {
		free(res->results);
		free(res);
		return out;
	} else {
		fprintf(stderr, "rent_execute_find(), failed - multiple results (%d)\n", res->count);
		mysql_res_free(&res);
		return NULL;
	}

	#undef QUERY
	#undef PARAM_COUNT
}


/* Generated function */
int rent_update(MYSQL* conn, RENT* rentT) {
	#define QUERY "update rent set id_reader = ?, id_book_specimen = ?, due_date = ? where id_rent = ?;"
	#define PARAM_COUNT 4
	#define STRING_SIZE 255
	assert(rentT->id_rent != 0);

	if (conn == NULL) {
		conn = db_init();
	}
	

	int retval;

	/* Generated using col_update_params() */
	MYSQL_BIND param[PARAM_COUNT];
	memset(&param, 0, sizeof(param));
	
	/* INTEGER PARAM */
	param[0].buffer = malloc(sizeof(uint));
	param[0].buffer_type = MYSQL_TYPE_LONG;
	memcpy(param[0].buffer, &rentT->reader->id_reader, sizeof(uint));
	/* INTEGER PARAM */
	param[1].buffer = malloc(sizeof(uint));
	param[1].buffer_type = MYSQL_TYPE_LONG;
	memcpy(param[1].buffer, &rentT->book_specimen->id_book_specimen, sizeof(uint));
	/* DATE PARAM */
	param[2].buffer = malloc(56);
	param[2].buffer_type = MYSQL_TYPE_DATE;
	mysql_timecpy(param[2].buffer, &rentT->due_date);
	/* INTEGER PARAM */
	param[3].buffer = malloc(sizeof(uint));
	param[3].buffer_type = MYSQL_TYPE_LONG;
	memcpy(param[3].buffer, &rentT->id_rent, sizeof(uint));

	retval = rent_execute(conn, QUERY, param, PARAM_COUNT);

	/* Generated using col_buffer_free() */
	free(param[0].buffer);
	free(param[1].buffer);
	free(param[2].buffer);
	free(param[3].buffer);
	

	return retval;

	#undef QUERY
	#undef PARAM_COUNT
	#undef STRING_SIZE
}


/* Generated function */
int rent_execute(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count) {
	#define QUERY_LENGTH 512
	/* Generated by body_execute */

	MYSQL_STMT* stmt;
	int retval;

	if (conn == NULL) {
		conn = db_init();
	}
	

	
	stmt = mysql_stmt_init(conn);

	if ((retval = mysql_stmt_prepare(stmt, query, strnlen(query, QUERY_LENGTH)))) {
		fprintf(stderr, "mysql_stmt_prepare(), failed\n");
		fprintf(stderr, "%s\n", mysql_error(conn));
		return retval;
	}

	if ((retval = mysql_stmt_bind_param(stmt, params))) {
		fprintf(stderr, "mysql_stmt_bind_param(), failed\n");
		fprintf(stderr, "%s\n", mysql_error(conn));
		return retval;
	}

	if ((retval = mysql_stmt_execute(stmt))) {
		fprintf(stderr, "mysql_stmt_execute(), failed\n");
		fprintf(stderr, "%s\n", mysql_error(conn));
		return retval;
	}

	if ((retval = mysql_stmt_close(stmt))) {
		fprintf(stderr, " failed while closing the statement\n");
		fprintf(stderr, " %s\n", mysql_error(conn));
		return retval;
	}

	#undef QUERY_LENGTH
}


/* Generated function */
int rent_delete(MYSQL* conn, RENT* rentT) {
	#define QUERY "delete from rent where id_rent = ?;"
	#define PARAM_COUNT 1
	assert(rentT->id_rent != 0);

	if (conn == NULL) {
		conn = db_init();
	}
	

	int retval;

	/* Generated using  get_col_param_buffers() */
	MYSQL_BIND param[PARAM_COUNT];
	memset(param, 0, sizeof(param));
	
	/* INTEGER PARAM */
	param[0].buffer = malloc(sizeof(uint));
	param[0].buffer_type = MYSQL_TYPE_LONG;
	memcpy(param[0].buffer, &rentT->id_rent, sizeof(uint));

	retval = rent_execute(conn, QUERY, param, PARAM_COUNT);

	/* Generated using col_param_buffer_free() */
	free(param[0].buffer);
	

	return retval;

	#undef QUERY
	#undef PARAM_COUNT
}


/* Generated function */
SQL_RESULT* rent_find_all(MYSQL* conn) {
	#define QUERY "select * from rent;"
	#define PARAM_COUNT 0
	SQL_RESULT* res;

	MYSQL_BIND param[1];

	if (conn == NULL) {
		conn = db_init();
	}
	

	res = rent_execute_find(conn, QUERY, param, PARAM_COUNT);

	return res;

	#undef QUERY
	#undef PARAM_COUNT
}


/* Generated function */
void rent_free(RENT** ptr) {
	/* Generated by get_free_members() */
	assert(ptr != NULL);
	
	if (*ptr != NULL){
		reader_free(&((*ptr)->reader));
		book_specimen_free(&((*ptr)->book_specimen));
		free(*ptr);
	}

}
