/**
 * Generated by nik on 04/01/2020
 */
#ifndef __nik_LIBRARY_DB_ENTITY_STRUCT_AUTHOR_BOOK_H
#define __nik_LIBRARY_DB_ENTITY_STRUCT_AUTHOR_BOOK_H

#pragma once


#include "db/orm/entity.h"

struct author_book {
	uint id_author_book;
	struct book* book;
	struct author* author;
};

typedef struct author_book AUTHOR_BOOK;

uint author_book_insert(MYSQL* conn, AUTHOR_BOOK* author_bookT);

SQL_RESULT* author_book_execute_find(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count);

AUTHOR_BOOK* author_book_find_by_id(MYSQL* conn, uint id);

int author_book_update(MYSQL* conn, AUTHOR_BOOK* author_bookT);

int author_book_execute(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count);

int author_book_delete(MYSQL* conn, AUTHOR_BOOK* author_bookT);

SQL_RESULT* author_book_find_all(MYSQL* conn);

void author_book_free(AUTHOR_BOOK** ptr);

#endif
