/**
 * Generated by nik on 04/01/2020
 */
#ifndef __nik_LIBRARY_DB_ENTITY_STRUCT_AUTHOR_H
#define __nik_LIBRARY_DB_ENTITY_STRUCT_AUTHOR_H

#pragma once


#include "db/orm/entity.h"

struct author {
	uint id_author;
	struct person* person;
	char description[4097];
};

typedef struct author AUTHOR;

uint author_insert(MYSQL* conn, AUTHOR* authorT);

SQL_RESULT* author_execute_find(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count);

AUTHOR* author_find_by_id(MYSQL* conn, uint id);

int author_update(MYSQL* conn, AUTHOR* authorT);

int author_execute(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count);

int author_delete(MYSQL* conn, AUTHOR* authorT);

SQL_RESULT* author_find_all(MYSQL* conn);

void author_free(AUTHOR** ptr);

#endif
