/**
 * Generated by nik on 04/01/2020
 */
#ifndef __nik_LIBRARY_DB_ENTITY_STRUCT_BOOK_SPECIMEN_H
#define __nik_LIBRARY_DB_ENTITY_STRUCT_BOOK_SPECIMEN_H

#pragma once


#include "db/orm/entity.h"

struct book_specimen {
	uint id_book_specimen;
	struct library* library;
	struct book* book;
	char book_serial[17];
};

typedef struct book_specimen BOOK_SPECIMEN;

uint book_specimen_insert(MYSQL* conn, BOOK_SPECIMEN* book_specimenT);

SQL_RESULT* book_specimen_execute_find(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count);

BOOK_SPECIMEN* book_specimen_find_by_id(MYSQL* conn, uint id);

int book_specimen_update(MYSQL* conn, BOOK_SPECIMEN* book_specimenT);

int book_specimen_execute(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count);

int book_specimen_delete(MYSQL* conn, BOOK_SPECIMEN* book_specimenT);

SQL_RESULT* book_specimen_find_all(MYSQL* conn);

void book_specimen_free(BOOK_SPECIMEN** ptr);

#endif
