/**
 * Generated by nik on 04/01/2020
 */
#ifndef __nik_LIBRARY_DB_ENTITY_STRUCT_EMPLOYEE_H
#define __nik_LIBRARY_DB_ENTITY_STRUCT_EMPLOYEE_H

#pragma once


#include "db/orm/entity.h"

struct employee {
	uint id_employee;
	struct person* person;
	struct library* library;
	char position[33];
};

typedef struct employee EMPLOYEE;

uint employee_insert(MYSQL* conn, EMPLOYEE* employeeT);

SQL_RESULT* employee_execute_find(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count);

EMPLOYEE* employee_find_by_id(MYSQL* conn, uint id);

int employee_update(MYSQL* conn, EMPLOYEE* employeeT);

int employee_execute(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count);

int employee_delete(MYSQL* conn, EMPLOYEE* employeeT);

SQL_RESULT* employee_find_all(MYSQL* conn);

void employee_free(EMPLOYEE** ptr);

#endif
