/**
 * Generated by nik on 04/01/2020
 */
#ifndef __nik_LIBRARY_DB_ENTITY_STRUCT_REGION_H
#define __nik_LIBRARY_DB_ENTITY_STRUCT_REGION_H

#pragma once


#include "db/orm/entity.h"

struct region {
	uint id_region;
	char name[256];
};

typedef struct region REGION;

uint region_insert(MYSQL* conn, REGION* regionT);

SQL_RESULT* region_execute_find(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count);

REGION* region_find_by_id(MYSQL* conn, uint id);

int region_update(MYSQL* conn, REGION* regionT);

int region_execute(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count);

int region_delete(MYSQL* conn, REGION* regionT);

SQL_RESULT* region_find_all(MYSQL* conn);

void region_free(REGION** ptr);

#endif
