/**
 * Generated by nik on 04/01/2020
 */
#ifndef __nik_LIBRARY_DB_ENTITY_STRUCT_RENT_H
#define __nik_LIBRARY_DB_ENTITY_STRUCT_RENT_H

#pragma once


#include "db/orm/entity.h"

struct rent {
	uint id_rent;
	struct reader* reader;
	struct book_specimen* book_specimen;
	struct tm due_date;
};

typedef struct rent RENT;

uint rent_insert(MYSQL* conn, RENT* rentT);

SQL_RESULT* rent_execute_find(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count);

RENT* rent_find_by_id(MYSQL* conn, uint id);

int rent_update(MYSQL* conn, RENT* rentT);

int rent_execute(MYSQL* conn, char const* query, MYSQL_BIND* params, uint param_count);

int rent_delete(MYSQL* conn, RENT* rentT);

SQL_RESULT* rent_find_all(MYSQL* conn);

void rent_free(RENT** ptr);

#endif
